### ISSUE TITLE
サーバーを起動してコンソールを開くとエラーが出ている。

### ISSUE THREAD

**Issue by RedCatHuu** [DWC-BIGDREAMER/NaganoCAKE#14]
サーバーを起動してコンソールを開くと"Refused to load the ~中略~ because it violates the following Content Security Policy directive: "script-src 'unsafe-inline'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback."というエラー文が出ている。mainブランチでサーバーを立ててもやはり同じエラーが発生。
rails newした時点で詰んでいたっぽい？

**Comment by EOwRHgjWLA** [comment]
mainはまだ何も弄っていないので、それでエラーを吐く場合はNaganoCAKE側のエラーではない気がします？
こちらの環境ではおそらく確認できていないので、
- エラー全文
- コンソールのスクリーンショット
辺りがあると共有出来るかと思います。

**Comment by RedCatHuu** [comment]
![スクリーンショット 2023-12-14 135229](https://github.com/DWC-BIGDREAMER/NaganoCAKE/assets/148026462/c753a831-751c-4b8a-8bf9-ff6862610049)
