### ISSUE TITLE
エラー内容のコピー

### ISSUE THREAD

**Issue by DONSAN7** [DWC-BIGDREAMER/NaganoCAKE#37]
ActionView::SyntaxErrorInTemplate in Public::HomesController#top
Encountered a syntax error while rendering template: check <header>
<nav class="navbar navbar-expand-lg navbar-dark " style="background-color: #0e357f;">

<div class="container">
<a class="navbar-brand" href="/">
<%= image_tag src="logo_transparent_resize", size: '100x80' %>
</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNavDropdown">
<ul class="navbar-nav mr-auto">
<% if admin_signed_in? %>
<li>
<%= link_to destroy_admin_session_path, class: 'text-warning', method: :delete do %>
管理者
<% end %>
</li>
<% else %>
<li>
<%= link_to admin_session_path, class: 'text-warning' do %>
管理者
<% end %>
</li>
<% end %>
<li>
<%= link_to admin_items_path,class: 'nav-link text-light' do %>
商品一覧
<% end %>
</li>
<li>
<%= link_to admin_customers_path,class: 'nav-link text-light' do %>
<i class="fas fa-users"></i> 会員一覧
<% end %>
</li>
<li>
<<<<<<< HEAD
<%= link_to admin_orders_path, class: 'nav-link text-light' do %>
注文履歴一覧
=======
<%= link_to admin_root_path, class: 'nav-link text-light' do %>
</i> 注文履歴一覧
>>>>>>> origin/develop
<% end %>
</li>
<li>
<%= link_to admin_genres_path ,class: 'nav-link text-light' do %>
ジャンル一覧
<% end %>
</li>
</ul>
<ul class="navbar-nav mr-auto">
<li class='text-warning'>客</li>
<li>
<%= link_to about_path,class: 'nav-link text-light' do %>
<i class="fas fa-link"></i> About
<% end %>
</li>
<li>
<%= link_to items_path,class: 'nav-link text-light' do %>
商品一覧
<% end %>
</li>
<li>
<%= link_to new_customer_registration_path,class: 'nav-link text-light' do %>
<i class="fas fa-user-plus"></i> 新規登録
<% end %>
</li>
<li>
<%= link_to new_customer_session_path ,class: 'nav-link text-light' do %>
<i class="fas fa-sign-in-alt"></i> ログイン
<% end %>
</li>
<li>
<%= link_to destroy_customer_session_path, method: :delete,class: 'nav-link text-light' do %>
<i class="fas fa-sign-out-alt"></i> Log out
<% end %>
</li>
</ul>
</div>
</div>
</nav>
<div style="height: 10px; background-color: #f9bb02"></div>
</header>

**Comment by EOwRHgjWLA** [comment]
コンフリクト発生時の記述が残っていたため、syntaxerrorが生じている？
→削除にて解決した模様
